atp_tour:
  outputs:
    dev:
      type: duckdb
      path: atp_tour.duckdb
      schema: fbalseiro
      threads: 1
    ci:
      type: duckdb
      path: atp_tour.duckdb
      schema: fbalseiro
      threads: 1

  target: dev
